spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 2
        max-idle: 5
        max-active: 10
  session:
    store-type: redis
    redis:
      namespace: spring:session:tommy
    timeout: 60
  devtools:
    restart:
      enabled: true